=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/excel-imp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tjnetsky.com.cn"
xmlns="http://www.tjnetsky.com.cn"
elementFormDefault="qualified">
	<xs:simpleType name="stringtype">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="inttype">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	<xs:simpleType name="booltype">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	
	<xs:complexType name="nullType" mixed="true">
		<xs:attribute name="name" use="optional"/>
		<xs:attribute name="value" use="optional"/>
	</xs:complexType>
	<xs:complexType name="columntype">
		<xs:sequence>
			<xs:element name="columnName" type="stringtype"/>
			<xs:element name="index" type="nullType"/>
			<xs:element name="name" type="stringtype"/>
			<xs:element name="colName" type="stringtype"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnstype">
		<xs:sequence>
			<xs:element name="type" type="stringtype" />
			<xs:element name="titleRow" type="inttype"/>
			<xs:element name="column" type="columntype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tableInfotype">
		<xs:sequence>
			<xs:element name="sheetNum" type="inttype"/>
			<xs:element name="startRow" type="inttype"/>
			<xs:element name="endRow" type="nullType" minOccurs="0"/>
			<xs:element name="endFlag" type="nullType"/>
			<xs:element name="tableName" type="stringtype"/>
			<xs:element name="tableNameShow" type="stringtype"/>
			<xs:element name="fatherTables" type="stringtype"/>
			<xs:element name="columns" type="columnstype"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="exceltype">
		<xs:sequence>
			<xs:element name="tableInfo" type="tableInfotype"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- the only element in the document-->
	<xs:element name="excel" type="exceltype"/>
</xs:schema>

=== subzero1/rms/WebRoot/WEB-INF/importConfig/mbk_source.xml
<?xml version="1.0" encoding="GBK"?>
<excel
xmlns="http://www.tjnetsky.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"
>
	<!-- 定义导入文件中表格信息 -->
	<tableInfo>
		<!-- 表格信息所在sheet位于excel文件中位置 -->
		<sheetNum>0</sheetNum>
		<!-- 数据开始行 -->
		<startRow>1</startRow>
		<endRow/>
		<endFlag></endFlag>
		<!-- 表名称，对应持久化对象名称 -->
		<tableName>Td21_mbk</tableName>
		<!-- 表名称,用于显示 -->
		<tableNameShow>资源信息批量导入</tableNameShow>
		<!-- 本表对应的父表信息 -->
		<fatherTables>
		</fatherTables>
		<!-- 当前表字段信息 -->
		<columns>
			<!-- byIndex:按列所在位置获取,byName: 按标题行名称获取-->
			<type>byName</type>
			<!-- 标题行位置 -->
			<titleRow>0</titleRow>
			<column>
					<columnName>ZYBH</columnName>
					<index/>
					<name>资源编号</name>
					<colName>资源编号</colName>
			</column>
			<column>
					<columnName>ZYMC</columnName>
					<index/>
					<name>资源名称</name>
					<colName>资源名称</colName>
			</column>
			<column>
					<columnName>JSXZ</columnName>
					<index/>
					<name>建设性质</name>
					<colName>建设性质</colName>
			</column>
			<column>
				<columnName>JSFS</columnName>
				<index/>
				<name>建设方式</name>
				<colName>建设方式</colName>
			</column>
			<column>
					<columnName>LB</columnName>
					<index/>
					<name>类别</name>
					<colName>类别</colName>
			</column>
			<column>
					<columnName>SSDQ</columnName>
					<index/>
					<name>所属地区</name>
					<colName>所属地区</colName>
			</column>
			<column>
					<columnName>SSWG</columnName>
					<index/>
					<name>所属网格</name>
					<colName>所属网格</colName>
			</column>
			<column>
					<columnName>ZLDD</columnName>
					<index/>
					<name>坐落地点</name>
					<colName>坐落地点</colName>
			</column>
			<column>
					<columnName>JD</columnName>
					<index/>
					<name>经度</name>
					<colName>经度</colName>
			</column>
			<column>
					<columnName>WD</columnName>
					<index/>
					<name>纬度</name>
					<colName>纬度</colName>
			</column>
			<column>
					<columnName>TDBM</columnName>
					<index/>
					<name>谈点部门</name>
					<colName>谈点部门</colName>
			</column>
			<column>
					<columnName>TDR</columnName>
					<index/>
					<name>谈点人</name>
					<colName>谈点人</colName>
			</column>
			<column>
					<columnName>TDRDH</columnName>
					<index/>
					<name>谈点人电话</name>
					<colName>谈点人电话</colName>
			</column> 
			<column>
					<columnName>LXR</columnName>
					<index/>
					<name>联系人</name>
					<colName>联系人</colName>
			</column>
			<column>
					<columnName>LXRDH</columnName>
					<index/>
					<name>联系人电话</name>
					<colName>联系人电话</colName>
			</column> 
			<column>
					<columnName>SFGJ</columnName>
					<index/>
					<name>是否共建</name>
					<colName>是否共建</colName>
			</column>
			<column>
					<columnName>TDXTF</columnName>
					<index/>
					<name>谈点协调费</name>
					<colName>谈点协调费</colName>
			</column>
			<column>
					<columnName>QYSJ</columnName>
					<index/>
					<name>签约时间</name>
					<colName>签约时间</colName>
			</column>
			<column>
					<columnName>ZJ</columnName>
					<index/>
					<name>租金</name>
					<colName>租金</colName>
			</column>
			<column>
					<columnName>NX</columnName>
					<index/>
					<name>年限</name>
					<colName>年限</colName>
			</column>
			<column>
					<columnName>HTBH</columnName>
					<index/>
					<name>合同编号</name>
					<colName>合同编号</colName>
			</column>
			<column>
					<columnName>YZMC</columnName>
					<index/>
					<name>业主姓名</name>
					<colName>业主姓名</colName>
			</column>
			<column>
					<columnName>YZDH</columnName>
					<index/>
					<name>业主电话</name>
					<colName>业主电话</colName>
			</column>
			<column>
					<columnName>SFSFK</columnName>
					<index/>
					<name>是否首付款</name>
					<colName>是否首付款</colName>
			</column>
			<column>
					<columnName>JSDJ</columnName>
					<index/>
					<name>建设等级</name>
					<colName>建设等级</colName>
			</column>
			<column>
					<columnName>TDZQ</columnName>
					<index/>
					<name>谈点周期</name>
					<colName>谈点周期</colName>
			</column>
			<column>
					<columnName>FKZQ</columnName>
					<index/>
					<name>反馈周期</name>
					<colName>反馈周期</colName>
			</column>
			<column>
					<columnName>KCSJ</columnName>
					<index/>
					<name>勘察时间</name>
					<colName>勘察时间</colName>
			</column>
			<column>
					<columnName>ZYPFSJ</columnName>
					<index/>
					<name>资源派发时间</name>
					<colName>资源派发时间</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/wxry_tmp.xml
<?xml version="1.0" encoding="GBK"?>
<excel
xmlns="http://www.tjnetsky.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"
>
	<!-- 定义导入文件中表格信息 -->
	<tableInfo>
		<!-- 表格信息所在sheet位于excel文件中位置 -->
		<sheetNum>0</sheetNum>
		<!-- 数据开始行 -->
		<startRow>1</startRow>
		<endRow/>
		<endFlag></endFlag>
		<!-- 表名称，对应持久化对象名称 -->
		<tableName>Tf30_wxyr</tableName>
		<!-- 表名称,用于显示 -->
		<tableNameShow>资源信息批量导入</tableNameShow>
		<!-- 本表对应的父表信息 -->
		<fatherTables>
		</fatherTables>
		<!-- 当前表字段信息 -->
		<columns>
			<!-- byIndex:按列所在位置获取,byName: 按标题行名称获取-->
			<type>byName</type>
			<!-- 标题行位置 -->
			<titleRow>0</titleRow>
			<column>
					<columnName>NAME</columnName>
					<index/>
					<name>姓名</name>
					<colName>姓名</colName>
			</column>
			<column>
					<columnName>SEX</columnName>
					<index/>
					<name>性别</name>
					<colName>性别</colName>
			</column>
			<column>
					<columnName>MOBILE</columnName>
					<index/>
					<name>移动电话</name>
					<colName>移动电话</colName>
			</column>
			<column>
					<columnName>SFZ</columnName>
					<index/>
					<name>身份证</name>
					<colName>身份证</colName>
			</column>
			<column>
					<columnName>ADDRESS</columnName>
					<index/>
					<name>住址</name>
					<colName>住址</colName>
			</column>
			<column>
					<columnName>STATUS</columnName>
					<index/>
					<name>状态</name>
					<colName>状态</colName>
			</column>
			<column>
					<columnName>BZ</columnName>
					<index/>
					<name>备注</name>
					<colName>备注</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td00_order.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td00_gcxx</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>SSDQ</columnName>
				<index />
				<name>所属地区</name>
				<colName>所属地区</colName>
			</column>
			<column>
				<columnName>LXXX</columnName>
				<index />
				<name>联系信息</name>
				<colName>联系信息</colName>
			</column>
			<column>
				<columnName>A_ADRESS</columnName>
				<index />
				<name>地址</name>
				<colName>地址</colName>
			</column> 
			<column>
				<columnName>CJRQ</columnName>
				<index />
				<name>到岗时间</name>
				<colName>到岗时间</colName>
			</column>  
			<column>
				<columnName>SGDW</columnName>
				<index />
				<name>施工单位</name>
				<colName>施工单位</colName>
			</column>
			<column>
				<columnName>WCFGQBM</columnName>
				<index />
				<name>完成分光器编码</name>
				<colName>完成分光器编码</colName>
			</column>
			<column>
				<columnName>WCSJ</columnName>
				<index />
				<name>完成时间</name>
				<colName>完成时间</colName>
			</column>
			<column>
				<columnName>HDBZ</columnName>
				<index />
				<name>备注</name>
				<colName>备注</colName>
			</column>
			<column>
				<columnName>GDZTZT</columnName>
				<index />
				<name>工单整体状态</name>
				<colName>工单整体状态</colName>
			</column>
			<column>
				<columnName>JHJGSJ</columnName>
				<index />
				<name>要求完成时间</name>
				<colName>要求完成时间</colName>
			</column>
			<column>
				<columnName>GCBH</columnName>
				<index />
				<name>订单编号</name>
				<colName>订单编号</colName>
			</column>  
			<column>
				<columnName>SFTS</columnName>
				<index />
				<name>是否投诉</name>
				<colName>是否投诉</colName>
			</column>
			<column>
				<columnName>SFCQ</columnName>
				<index />
				<name>是否超期</name>
				<colName>是否超期</colName>
			</column>  
			<column>
				<columnName>XMGLY</columnName>
				<index />
				<name>项目管理员</name>
				<colName>项目管理员</colName>
			</column>  
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/WebRoot/WEB-INF/importConfig/import_rckh.xml
<?xml version="1.0" encoding="GBK"?>
<excel
xmlns="http://www.tjnetsky.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"
>
	<!-- 定义导入文件中表格信息 -->
	<tableInfo>
		<!-- 表格信息所在sheet位于excel文件中位置 -->
		<sheetNum>0</sheetNum>
		<!-- 数据开始行 -->
		<startRow>1</startRow>
		<endRow/>
		<endFlag></endFlag>
		<!-- 表名称，对应持久化对象名称 -->
		<tableName>Tf17_rckh</tableName>
		<!-- 表名称,用于显示 -->
		<tableNameShow>日常考核导入</tableNameShow>
		<!-- 本表对应的父表信息 -->
		<fatherTables>
		</fatherTables>
		<!-- 当前表字段信息 -->
		<columns>
			<!-- byIndex:按列所在位置获取,byName: 按标题行名称获取-->
			<type>byName</type>
			<!-- 标题行位置 -->
			<titleRow>0</titleRow>
			<column>
					<columnName>ID</columnName>
					<index/>
					<name>唯一标识</name>
					<colName>唯一标识</colName>
			</column>
			<column>
					<columnName>WXDW_MC</columnName>
					<index/>
					<name>合作单位</name>
					<colName>合作单位</colName>
			</column>
			<column>
					<columnName>KHRY_NAME</columnName>
					<index/>
					<name>考核人员</name>
					<colName>考核人员</colName>
			</column>
			<column>
				<columnName>KHLB</columnName>
				<index/>
				<name>考核归类</name>
				<colName>考核归类</colName>
			</column>
			<column>
					<columnName>KHDZ</columnName>
					<index/>
					<name>考核类别</name>
					<colName>考核类别</colName>
			</column>
			<column>
					<columnName>FKJE</columnName>
					<index/>
					<name>考核金额</name>
					<colName>考核金额</colName>
			</column>
			<column>
					<columnName>JKFZ</columnName>
					<index/>
					<name>考核分值</name>
					<colName>考核分值</colName>
			</column>
			<column>
					<columnName>KHYY</columnName>
					<index/>
					<name>考核原因</name>
					<colName>考核原因</colName>
			</column>
			<column>
					<columnName>KHJG</columnName>
					<index/>
					<name>考核结果</name>
					<colName>考核结果</colName>
			</column>
			<column>
					<columnName>KHSJ</columnName>
					<index/>
					<name>考核时间</name>
					<colName>考核时间</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf30_wxry.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName />
		<tableNameShow>TF30_WXRY</tableNameShow>
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>NAME</columnName>
				<index />
				<name>姓名</name>
				<colName>姓名</colName>
			</column>
			<column>
				<columnName>SEX</columnName>
				<index />
				<name>性别</name>
				<colName>性别</colName>
			</column>
			<column>
				<columnName>MOBILE</columnName>
				<index />
				<name>移动电话</name>
				<colName>移动电话</colName>
			</column>
			<column>
				<columnName>SFZ</columnName>
				<index />
				<name>身份证</name>
				<colName>身份证</colName>
			</column>
			<column>
				<columnName>ADDRESS</columnName>
				<index />
				<name>住址</name>
				<colName>住址</colName>
			</column> 
			<column>
				<columnName>WXDW_ID</columnName>
				<index />
				<name>外协单位</name>
				<colName>外协单位</colName>
			</column>
			<column>
				<columnName>STATUS</columnName>
				<index />
				<name>状态</name>
				<colName>状态</colName>
			</column>
			<column>
				<columnName>BX</columnName>
				<index />
				<name>本部/下挂单位</name>
				<colName>本部/下挂单位</colName>
			</column>
			<column>
				<columnName>MAJOR</columnName>
				<index />
				<name>专业</name>
				<colName>专业</colName>
			</column>
			<column>
				<columnName>CONTRACT</columnName>
				<index />
				<name>是否签订劳动合同</name>
				<colName>是否签订劳动合同</colName>
			</column>
			<column>
				<columnName>INSURE</columnName>
				<index />
				<name>是否上保险</name>
				<colName>是否上保险</colName>
			</column>
			<column>
				<columnName>SAFETY</columnName>
				<index />
				<name>安全保护用品是否派发</name>
				<colName>安全保护用品是否派发</colName>
			</column>
			<column>
				<columnName>GYSZ</columnName>
				<index />
				<name>概预算证</name>
				<colName>概预算证</colName>
			</column>
			<column>
				<columnName>AQYZ</columnName>
				<index />
				<name>安全员证</name>
				<colName>安全员证</colName>
			</column>
			<column>
				<columnName>JLZ</columnName>
				<index />
				<name>监理证</name>
				<colName>监理证</colName>
			</column>
			<column>
				<columnName>DGZ</columnName>
				<index />
				<name>登高证</name>
				<colName>登高证</colName>
			</column>
			<column>
				<columnName>EC</columnName>
				<index />
				<name>电工证</name>
				<colName>电工证</colName>
			</column>
			<column>
				<columnName>BZ</columnName>
				<index />
				<name>备注</name>
				<colName>备注</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/zytlr.xml
<?xml version="1.0" encoding="GBK"?>
<excel
xmlns="http://www.tjnetsky.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"
>
	<!-- 定义导入文件中表格信息 -->
	<tableInfo>
		<!-- 表格信息所在sheet位于excel文件中位置 -->
		<sheetNum>0</sheetNum>
		<!-- 数据开始行 -->
		<startRow>1</startRow>
		<endRow/>
		<endFlag></endFlag>
		<!-- 表名称，对应持久化对象名称 -->
		<tableName>Tf31_zytl</tableName>
		<!-- 表名称,用于显示 -->
		<tableNameShow>资源信息批量导入</tableNameShow>
		<!-- 本表对应的父表信息 -->
		<fatherTables>
		</fatherTables>
		<!-- 当前表字段信息 -->
		<columns>
			<!-- byIndex:按列所在位置获取,byName: 按标题行名称获取-->
			<type>byName</type>
			<!-- 标题行位置 -->
			<titleRow>0</titleRow>
			<column>
					<columnName>GIS_NO</columnName>
					<index/>
					<name>GIS系统工号</name>
					<colName>GIS系统工号</colName>
			</column>
			<column>
					<columnName>TLRXM</columnName>
					<index/>
					<name>填录人姓名</name>
					<colName>填录人姓名</colName>
			</column>
			<column>
					<columnName>SSDW</columnName>
					<index/>
					<name>所属单位</name>
					<colName>所属单位</colName>
			</column>
			<column>
				<columnName>NX</columnName>
				<index/>
				<name>年限</name>
				<colName>年限</colName>
			</column>
			<column>
					<columnName>IN_TIME</columnName>
					<index/>
					<name>进入建设中心日期</name>
					<colName>进入建设中心日期</colName>
			</column>
			<column>
					<columnName>RZCJ</columnName>
					<index/>
					<name>认证成绩</name>
					<colName>认证成绩</colName>
			</column>
			<column>
					<columnName>PHONE</columnName>
					<index/>
					<name>联系电话</name>
					<colName>联系电话</colName>
			</column>
			<column>
					<columnName>ZC</columnName>
					<index/>
					<name>专长(管道,电缆,光缆)</name>
					<colName>专长(管道,电缆,光缆)</colName>
			</column>
			<column>
					<columnName>ZCQK</columnName>
					<index/>
					<name>在册情况</name>
					<colName>在册情况</colName>
			</column>
			<column>
					<columnName>BZ</columnName>
					<index/>
					<name>备注</name>
					<colName>备注</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td56_event.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td56_event</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow>
			<column>
				<columnName>ID</columnName>
				<index />
				<name>标志</name>
				<colName>标志</colName>
			</column>
			<column>
				<columnName>NODE</columnName>
				<index />
				<name>环节</name>
				<colName>环节</colName>
			</column>
			<column>
				<columnName>SJMC</columnName>
				<index />
				<name>事件名称</name>
				<colName>事件名称</colName>
			</column>
			<column>
				<columnName>GDZT</columnName>
				<index />
				<name>工单状态</name>
				<colName>工单状态</colName>
			</column>
			<column>
				<columnName>JSR</columnName>
				<index />
				<name>接收人</name>
				<colName>接收人</colName>
			</column>
			<column>
				<columnName>CLR</columnName>
				<index />
				<name>处理人</name>
				<colName>处理人</colName>
			</column>
			<column>
				<columnName>WCSJ</columnName>
				<index />
				<name>完成时间</name>
				<colName>完成时间</colName>
			</column>
			<column>
				<columnName>CLJG</columnName>
				<index />
				<name>处理结果</name>
				<colName>处理结果</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf43_gdcqtj.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Tf43_temp</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<title>工单超期情况统计</title>
			<column>
				<columnName>C1</columnName>
				<index />
				<name></name>
				<colName>区域\月份</colName>
			</column>
			<column>
				<columnName>C2</columnName>
				<index />
				<name>1月</name>
				<colName>1月</colName>
			</column>
			<column>
				<columnName>C3</columnName>
				<index />
				<name>2月</name>
				<colName>2月</colName>
			</column>
			<column>
				<columnName>C4</columnName>
				<index />
				<name>3月</name>
				<colName>3月</colName>
			</column>
			<column>
				<columnName>C5</columnName>
				<index />
				<name>4月</name>
				<colName>4月</colName>
			</column>
			<column>
				<columnName>C6</columnName>
				<index />
				<name>5月</name>
				<colName>5月</colName>
			</column>
			<column>
				<columnName>C7</columnName>
				<index />
				<name>6月</name>
				<colName>6月</colName>
			</column>
			<column>
				<columnName>C8</columnName>
				<index />
				<name>7月</name>
				<colName>7月</colName>
			</column>
			<column>
				<columnName>C9</columnName>
				<index />
				<name>8月</name>
				<colName>8月</colName>
			</column>
			<column>
				<columnName>C10</columnName>
				<index />
				<name>9月</name>
				<colName>9月</colName>
			</column>
			<column>
				<columnName>C11</columnName>
				<index />
				<name>10月</name>
				<colName>10月</colName>
			</column>
			<column>
				<columnName>C12</columnName>
				<index />
				<name>11月</name>
				<colName>11月</colName>
			</column>
			<column>
				<columnName>C13</columnName>
				<index />
				<name>12月</name>
				<colName>12月</colName>
			</column>
			<column>
				<columnName>C14</columnName>
				<index />
				<name>小计</name>
				<colName>小计</colName>
			</column>
			<column>
				<columnName>C15</columnName>
				<index />
				<name>区域工单量</name>
				<colName>区域工单量</colName>
			</column>
			<column>
				<columnName>C16</columnName>
				<index />
				<name>区域占比</name>
				<colName>区域占比</colName>
			</column>
		</columns>
	</tableInfo>
</excel>
