=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/excel-imp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.tjnetsky.com.cn"
xmlns="http://www.tjnetsky.com.cn"
elementFormDefault="qualified">
	<xs:simpleType name="stringtype">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="inttype">
		<xs:restriction base="xs:integer"/>
	</xs:simpleType>
	<xs:simpleType name="booltype">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	
	<xs:complexType name="nullType" mixed="true">
		<xs:attribute name="name" use="optional"/>
		<xs:attribute name="value" use="optional"/>
	</xs:complexType>
	<xs:complexType name="columntype">
		<xs:sequence>
			<xs:element name="columnName" type="stringtype"/>
			<xs:element name="index" type="nullType"/>
			<xs:element name="name" type="stringtype"/>
			<xs:element name="colName" type="stringtype"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnstype">
		<xs:sequence>
			<xs:element name="type" type="stringtype" />
			<xs:element name="titleRow" type="inttype"/>
			<xs:element name="column" type="columntype" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="tableInfotype">
		<xs:sequence>
			<xs:element name="sheetNum" type="inttype"/>
			<xs:element name="startRow" type="inttype"/>
			<xs:element name="endRow" type="nullType" minOccurs="0"/>
			<xs:element name="endFlag" type="nullType"/>
			<xs:element name="tableName" type="stringtype"/>
			<xs:element name="tableNameShow" type="stringtype"/>
			<xs:element name="fatherTables" type="stringtype"/>
			<xs:element name="columns" type="columnstype"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="exceltype">
		<xs:sequence>
			<xs:element name="tableInfo" type="tableInfotype"/>
		</xs:sequence>
	</xs:complexType>
	
	<!-- the only element in the document-->
	<xs:element name="excel" type="exceltype"/>
</xs:schema>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf43_xmglyDownAndTimeout.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Tf43_temp</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow>
			<column>
				<columnName>ID</columnName>
				<index />
				<name>序号</name>
				<colName>序号</colName>
			</column>
			<column>
				<columnName>C1</columnName>
				<index />
				<name>项目管理员</name>
				<colName>项目管理员</colName>
			</column>
			<column>
				<columnName>C2</columnName>
				<index />
				<name>项目数</name>
				<colName>项目数</colName>
			</column>
			<column>
				<columnName>C3</columnName>
				<index />
				<name>派设计数</name>
				<colName>派设计数</colName>
			</column>
			<column>
				<columnName>C4</columnName>
				<index />
				<name>派施工数</name>
				<colName>派施工数</colName>
			</column>
			<column>
				<columnName>C5</columnName>
				<index />
				<name>派监理数</name>
				<colName>派监理数</colName>
			</column>
			<column>
				<columnName>C6</columnName>
				<index />
				<name>施工超期数</name>
				<colName>施工超期数</colName>
			</column>
			<column>
				<columnName>C7</columnName>
				<index />
				<name>施工超期率</name>
				<colName>施工超期率</colName>
			</column>
			<column>
				<columnName>C8</columnName>
				<index />
				<name>决算数</name>
				<colName>决算数</colName>
			</column>
			<column>
				<columnName>C9</columnName>
				<index />
				<name>决算率</name>
				<colName>决算率</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td01_xmxx.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td01_xmxx</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>XMMC</columnName>
				<index />
				<name>项目名称</name>
				<colName>项目名称</colName>
			</column>
			<column>
				<columnName>XMBH</columnName>
				<index />
				<name>项目编号</name>
				<colName>项目编号</colName>
			</column>
			<column>
				<columnName>SSDQ</columnName>
				<index />
				<name>所属地区</name>
				<colName>所属地区</colName>
			</column>
			<column>
				<columnName>GCLB</columnName>
				<index />
				<name>工程类别</name>
				<colName>工程类别</colName>
			</column> 
			<column>
				<columnName>SGDW</columnName>
				<index />
				<name>施工单位</name>
				<colName>施工单位</colName>
			</column>
			<column>
				<columnName>SGHTBH</columnName>
				<index />
				<name>施工合同编号</name>
				<colName>施工合同编号</colName>
			</column> 
			<column>
				<columnName>SGHTJE</columnName>
				<index />
				<name>施工合同金额</name>
				<colName>施工合同金额</colName>
			</column> 
			<column>
				<columnName>XMZT</columnName>
				<index />
				<name>项目状态</name>
				<colName>项目状态</colName>
			</column> 
			<column>
				<columnName>XMJL</columnName>
				<index />
				<name>项目经理</name>
				<colName>项目经理</colName>
			</column> 
			<column>
				<columnName>LXJE</columnName>
				<index />
				<name>立项金额</name>
				<colName>立项金额</colName>
			</column> 
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td52_aqys.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td52_aqys</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>IPA</columnName>
				<index />
				<name>ip地址</name>
				<colName>ip地址</colName>
			</column>
			<column>
				<columnName>PORT_NUM</columnName>
				<index />
				<name>端口号</name>
				<colName>端口号</colName>
			</column>
			<column>
				<columnName>LOGIN_PROTOCOL</columnName>
				<index />
				<name>登录协议</name>
				<colName>登录协议</colName>
			</column>
			<column>
				<columnName>USERNAME</columnName>
				<index />
				<name>用户名</name>
				<colName>用户名</colName>
			</column>
			<column>
				<columnName>USERPWD</columnName>
				<index />
				<name>用户密码</name>
				<colName>用户密码</colName>
			</column>
			<column>
				<columnName>SUP_USERNAME</columnName>
				<index />
				<name>超级用户账号</name>
				<colName>超级用户账号</colName>
			</column>
			<column>
				<columnName>SUP_USERPWD</columnName>
				<index />
				<name>超级用户密码</name>
				<colName>超级用户密码</colName>
			</column>
			<column>
				<columnName>DEVICE_TYPE</columnName>
				<index />
				<name>设备类型</name>
				<colName>设备类型</colName>
			</column> 
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td55_order.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td55_order</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow>
			<column>
				<columnName>ID</columnName>
				<index />
				<name>标识</name>
				<colName>标识</colName>
			</column>
			<column>
				<columnName>DDBM</columnName>
				<index />
				<name>订单编码</name>
				<colName>订单编码</colName>
			</column>
			<column>
				<columnName>GSDQ</columnName>
				<index />
				<name>归属地区</name>
				<colName>归属地区</colName>
			</column>
			<column>
				<columnName>SERVICE</columnName>
				<index />
				<name>服務</name>
				<colName>服務</colName>
			</column>
			<column>
				<columnName>DDZT</columnName>
				<index />
				<name>订单状态</name>
				<colName>订单状态</colName>
			</column>
			<column>
				<columnName>DDLX</columnName>
				<index />
				<name>订单类型</name>
				<colName>订单类型</colName>
			</column>
			<column>
				<columnName>DDFL</columnName>
				<index />
				<name>订单分类</name>
				<colName>订单分类</colName>
			</column>
			<column>
				<columnName>YWKTDJ</columnName>
				<index />
				<name>业务开通等级</name>
				<colName>业务开通等级</colName>
			</column>
			<column>
				<columnName>BZFWDJ</columnName>
				<index />
				<name>保障服务等级</name>
				<colName>保障服务等级</colName>
			</column>
			<column>
				<columnName>WLFWDJ</columnName>
				<index />
				<name>网络服务等级</name>
				<colName>网络服务等级</colName>
			</column>
			<column>
				<columnName>FWDDLX</columnName>
				<index />
				<name>服务订单类型</name>
				<colName>服务订单类型</colName>
			</column>
			<column>
				<columnName>KHLB</columnName>
				<index />
				<name>客户类别</name>
				<colName>客户类别</colName>
			</column>
			<column>
				<columnName>YQYWKTSJ</columnName>
				<index />
				<name>要求业务开通时间</name>
				<colName>要求业务开通时间</colName>
			</column>
			<column>
				<columnName>SLSJ</columnName>
				<index />
				<name>受理时间</name>
				<colName>受理时间</colName>
			</column>
			<column>
				<columnName>SLR</columnName>
				<index />
				<name>受理人</name>
				<colName>受理人</colName>
			</column>
			<column>
				<columnName>YWZYSJ</columnName>
				<index />
				<name>业务租用到期时间</name>
				<colName>业务租用到期时间</colName>
			</column>
			<column>
				<columnName>ZXH</columnName>
				<index />
				<name>专线号</name>
				<colName>专线号</colName>
			</column>
			<column>
				<columnName>THEME</columnName>
				<index />
				<name>主题</name>
				<colName>主题</colName>
			</column>
			<column>
				<columnName>XQMS</columnName>
				<index />
				<name>需求描述</name>
				<colName>需求描述</colName>
			</column>
			<column>
				<columnName>LXXX</columnName>
				<index />
				<name>联系信息</name>
				<colName>联系信息</colName>
			</column>
			<column>
				<columnName>BZ</columnName>
				<index />
				<name>备注</name>
				<colName>备注</colName>
			</column>
			<column>
				<columnName>SLAVE_ID</columnName>
				<index />
				<name>附件表标识</name>
				<colName>附件表标识</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf01_wxdw.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Tf01_wxdw</tableName>
		<tableNameShow>Tf01_wxdw</tableNameShow>
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>MC</columnName>
				<index />
				<name>名称</name>
				<colName>名称</colName>
			</column>
			<column>
				<columnName>DWDZ</columnName>
				<index />
				<name>地址</name>
				<colName>地址</colName>
			</column>
			<column>
				<columnName>ZZDJ</columnName>
				<index />
				<name>资质等级</name>
				<colName>资质等级</colName>
			</column>
			<column>
				<columnName>FR</columnName>
				<index />
				<name>法人</name>
				<colName>法人</colName>
			</column>
			<column>
				<columnName>LB</columnName>
				<index />
				<name>类别</name>
				<colName>类别</colName>
			</column>  
			<column>
				<columnName>QY</columnName>
				<index />
				<name>区域</name>
				<colName>区域</colName>
			</column>
			<column>
				<columnName>ZY</columnName>
				<index />
				<name>专业</name>
				<colName>专业</colName>
			</column>
			<column>
				<columnName>BZ</columnName>
				<index />
				<name>备注</name>
				<colName>备注</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf43_gdsjhz.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Tf43_temp</tableName>
		<tableNameShow />
		<fatherTables />
		<title>工单数据汇总表</title>
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>C1</columnName>
				<index />
				<name>类别\月份</name>
				<colName>区域\月份</colName>
			</column>
			<column>
				<columnName>C2</columnName>
				<index />
				<name>1月</name>
				<colName>1月</colName>
			</column>
			<column>
				<columnName>C3</columnName>
				<index />
				<name>2月</name>
				<colName>2月</colName>
			</column>
			<column>
				<columnName>C4</columnName>
				<index />
				<name>3月</name>
				<colName>3月</colName>
			</column>
			<column>
				<columnName>C5</columnName>
				<index />
				<name>4月</name>
				<colName>4月</colName>
			</column>
			<column>
				<columnName>C6</columnName>
				<index />
				<name>5月</name>
				<colName>5月</colName>
			</column>
			<column>
				<columnName>C7</columnName>
				<index />
				<name>6月</name>
				<colName>6月</colName>
			</column>
			<column>
				<columnName>C8</columnName>
				<index />
				<name>7月</name>
				<colName>7月</colName>
			</column>
			<column>
				<columnName>C9</columnName>
				<index />
				<name>8月</name>
				<colName>8月</colName>
			</column>
			<column>
				<columnName>C10</columnName>
				<index />
				<name>9月</name>
				<colName>9月</colName>
			</column>
			<column>
				<columnName>C11</columnName>
				<index />
				<name>10月</name>
				<colName>10月</colName>
			</column>
			<column>
				<columnName>C12</columnName>
				<index />
				<name>11月</name>
				<colName>11月</colName>
			</column>
			<column>
				<columnName>C13</columnName>
				<index />
				<name>12月</name>
				<colName>12月</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/tf32_hzdw_status.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Tf32_hzdw_status</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow>
			<column>
				<columnName>ID</columnName>
				<index />
				<name>序号</name>
				<colName>序号</colName>
			</column>
			<column>
				<columnName>MC</columnName>
				<index />
				<name>合作单位</name>
				<colName>合作单位</colName>
			</column>
			<column>
				<columnName>PDS</columnName>
				<index />
				<name>派单数</name>
				<colName>派单数</colName>
			</column>
			<column>
				<columnName>JDS</columnName>
				<index />
				<name>接单数</name>
				<colName>接单数</colName>
			</column>
			<column>
				<columnName>SJXZS</columnName>
				<index />
				<name>实际选择数</name>
				<colName>实际选择数</colName>
			</column>
			<column>
				<columnName>XTXZS</columnName>
				<index />
				<name>系统选择数</name>
				<colName>系统选择数</colName>
			</column>
			<column>
				<columnName>CQS</columnName>
				<index />
				<name>超期数</name>
				<colName>超期数</colName>
			</column>
			<column>
				<columnName>CQL</columnName>
				<index />
				<name>超期率</name>
				<colName>超期率</colName>
			</column>
			<column>
				<columnName>JSS</columnName>
				<index />
				<name>决算数</name>
				<colName>决算数</colName>
			</column>
			<column>
				<columnName>JSL</columnName>
				<index />
				<name>决算率</name>
				<colName>决算率</colName>
			</column>
		</columns>
	</tableInfo>
</excel>

=== subzero1/rms/rms/WebRoot/WEB-INF/importConfig/td01_xmxxList.xml
<?xml version="1.0" encoding="UTF-8"?>
<excel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.tjnetsky.com.cn excel-imp.xsd"><!--定义导入文件中表格信息-->
	<tableInfo><!--表格信息所在sheet位于excel文件中位置-->
		<sheetNum>0</sheetNum>
		<startRow>1</startRow>
		<endRow />
		<endFlag />
		<tableName>Td01_xmxx</tableName>
		<tableNameShow />
		<fatherTables />
		<columns><!--当前表字段信息-->
			<type>byName</type>
			<titleRow>0</titleRow> 
			<column>
				<columnName>XMMC</columnName>
				<index />
				<name>项目名称</name>
				<colName>项目名称</colName>
			</column>
			<column>
				<columnName>XMBH</columnName>
				<index />
				<name>项目编号</name>
				<colName>项目编号</colName>
			</column>
			<column>
				<columnName>SSDQ</columnName>
				<index />
				<name>所属地区</name>
				<colName>所属地区</colName>
			</column>
			<column>
				<columnName>XMGLY</columnName>
				<index />
				<name>项目经理</name>
				<colName>项目经理</colName>
			</column> 
			<column>
				<columnName>SGDW</columnName>
				<index />
				<name>施工单位</name>
				<colName>施工单位</colName>
			</column>
			<column>
				<columnName>SJJGSJ</columnName>
				<index />
				<name>竣工时间</name>
				<colName>竣工时间</colName>
			</column> 
			<column>
				<columnName>JSSJ</columnName>
				<index />
				<name>决算时间</name>
				<colName>决算时间</colName>
			</column> 
			<column>
				<columnName>XMZT</columnName>
				<index />
				<name>项目状态</name>
				<colName>项目状态</colName>
			</column> 
		</columns>
	</tableInfo>
</excel>
